version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    target-branch: "main" # Create PRs against a specific branch
    schedule:
      interval: "weekly" # You can choose daily, weekly, or monthly
      day: "friday" # Specific day for weekly updates
      time: "10:00" # Specific time (in UTC)
      timezone: "Europe/Berlin" # Specific timezone

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "10:00"
      timezone: "Europe/Berlin"
    # Note: Dependabot will update action versions but not env vars like HUGO_VERSION
    # Consider using renovate for more advanced dependency management
