version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    target-branch: "main" # Create PRs against a specific branch
    schedule:
      interval: "weekly" # You can choose daily, weekly, or monthly
      day: "friday" # Specific day for weekly updates
      time: "10:00" # Specific time (in UTC)
      timezone: "Europe/Berlin" # Specific timezone
    versioning-strategy: increase-if-necessary # Only update to tagged versions
